name: Flake8

on:
  pull_request:
    branches-ignore:
      - 'docs/*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create Virtual Environment
        run: python3 -m venv venv

      - name: Activate Virtual Environment
        run: . venv/bin/activate

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8 src
